### ISSUE TITLE
custom width

### ISSUE THREAD

**Issue by turgutoztunc** [Minitour/AZDialogViewController#14]
How can i change the dialog width with custom views ?

**Comment by Minitour** [comment]
@turgutoztunc As of now you cannot adjust the width of the dialog, since the width is automatically determined based on the device you are using. However, when using a custom view you can adjust the aspect ratio of the custom view holder which will adjust the height of the dialog.

You can do it like so:
```swift
dialog.customViewSizeRatio = 0.2
```
this would mean that your custom view height to width proportion would be 2 : 10.
Let's say the device width is `x` and let's assume that the dialog width would be 80% of the device meaning `0.8 x`. This would mean that the height of the custom view would end up being `0.2 * 0.8 * x`
