### ISSUE TITLE
Flattened button sizes for iPhone X screen size.

### ISSUE THREAD

**Issue by HackShitUp** [Minitour/AZDialogViewController#15]
The UIButtons in the AZDialogViewController have buttons that are flattened and are not proportional to what the buttons should look like according to the readme for iPhone X screen sizes. Are you using the Safe Area layout guide?

**Comment by Minitour** [comment]
@HackShitUp Thanks for reporting, I'll look into it.

**Comment by HackShitUp** [comment]
@Minitour Thank you for making something so useful haha. Here's a URL I personally found useful for managing the new safe area layout guides: 
https://useyourloaf.com/blog/safe-area-layout-guide/
Hope it helps!

**Comment by HackShitUp** [comment]
@Minitour any updates with this?

**Comment by Minitour** [comment]
@HackShitUp I looked into it, and basically the heights of the buttons are calculated based on the device's height. Now I added an exception for iPhone X devices where instead of taking the entire screen, it would only take in the safe area view into calculations. 

In short the buttons' size is proportional.
