### ISSUE TITLE
Is there a way to know when dismiss() on the dialog is called?

### ISSUE THREAD

**Issue by ramonsgds** [Minitour/AZDialogViewController#24]
When I show my dialog to the user, he/she has two options:

1) Tap on "Yes" 
2) Tap on "Cancel" or just tap on the screen or move the dialog upwards or downwards.

Is there a way to absolutely cover the 2 option in one method, thereforing listening to the dismissal call?

Cancel and tap on screen (touchesBegan:) wouldn't be a problem to recognize, while upwards/downwards swipe/pan would be.

**Comment by Minitour** [comment]
You can dismiss with completion block:
https://github.com/Minitour/AZDialogViewController/blob/master/Sources/AZDialogViewController.swift#L542

**Comment by ramonsgds** [comment]
Is this method called automatically when the user swipes the dialog upwards/downwards? I need to cover all cases of whenever a dialog can be dismissed. So, it's more about listening to the dismiss by the user than actually calling `dismiss()` myself to force the dialog to dismiss.

**Comment by Minitour** [comment]
@ramonsgds Actually no, it doesn't invoke a completion block if you dismiss with gesture.
A workaround I suggest is, in the containing view controller (the one in which you are showing the dialog) Override the function `viewDidAppear`. It should get invoked every time the dialog is dismissed. (That is because when you are showing a dialog you are showing another view controller)
