### ISSUE TITLE
Re-Call Bug

### ISSUE THREAD

**Issue by zezeron** [Minitour/AZDialogViewController#28]
Hi Again;

I found another mistake while using it. If you make closure type initializing and many times `dialog.show(in: self)` method calling you then after the dismiss operation is goes a bug.

my code is here ---- 

[http://notes.io/m4ik](http://notes.io/m4ik)

**Comment by Minitour** [comment]
Use a function to construct a new dialog instead of re-using the same dialog.

**Comment by parveenkumardeeva** [comment]
Hi @Minitour ,

I think it's not working properly. I.e. If we have two different dialog instance and we are showing the second one after the dismissal of first one then it's not showing the second dialog.

For e.g: 
```
1.  let dialogLogout1 = AZDialogViewController(title: "First", message: "First Dialog")
     dialogLogout1.show(in: self)
2. dialogLogout1.dismiss()  
    let dialogLogout2 = AZDialogViewController(title: "Second", message: "Second Dialog")
    dialogLogout2.show(in: self)
//Into the same ViewController
```

Will you please check? Or I'm doing something wrong?  It's an urgent requirement for me.

**Comment by Minitour** [comment]
@parveenkumardeeva make sure to display the dialog in A completion block of the dismiss function.
You were having this issue because you were calling dismiss and then show right away, but you have to remember it takes few seconds to dismiss the dialog (due to the animation) therefor when you’re calling the show it’s basically still showing the older dialog.

**Comment by parveenkumardeeva** [comment]
@Minitour , Thanks for your quick reply and solution. It's working perfectly.
